from pathlib import Path
import psutil
import yaml
import sys
import io
import time
from threading import Event

# Force UTF-8 encoding for stdout
if sys.stdout.encoding != 'utf-8':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

from ..utils.emailer import send_email_alert

CONFIG_PATH = Path(__file__).resolve().parents[1] / "config" / "config.yaml"

# Load config.yaml for whitelist and blacklist
with open(CONFIG_PATH, "r") as f:
    config = yaml.safe_load(f)

WHITELIST = set(name.lower() for name in config.get("whitelist", []))
BLACKLIST = set(name.lower() for name in config.get("blacklist", []))

# Keywords common in malware names
SUSPICIOUS_KEYWORDS = [
    "malware", "keylogger", "stealer", "ransom",
    "rat", "spy", "inject", "virus", "hack", "ddos",
]

def monitor_processes(stop_event, config, callback=None):
    """
    Continuously monitor processes for suspicious activity.
    
    Args:
        stop_event: Threading event to control monitoring
        config: Dictionary containing monitoring configuration
        callback: Optional callback function for status updates
    """
    scan_count = 0
    last_all_clear_time = 0
    
    while not stop_event.is_set():
        scan_count += 1
        if callback:
            callback("scan_start", {"count": scan_count})
            
        suspicious_processes = scan_for_malware(stop_event)
        current_time = time.time()
        
        if suspicious_processes:
            if callback:
                callback("threats_found", {
                    "count": len(suspicious_processes),
                    "processes": suspicious_processes
                })
        elif current_time - last_all_clear_time >= 3600:  # Hourly all-clear
            if callback:
                callback("all_clear", None)
            last_all_clear_time = current_time
            
        if callback:
            callback("scan_complete", {"count": scan_count})
            
        # Wait for next scan
        for _ in range(config.get('monitor_interval_seconds', 5)):
            if stop_event.is_set():
                break
            time.sleep(1)

def scan_for_malware(stop_event=None):
    suspicious = []
    # Verbose by default; set CSBOT_DEBUG=0 to silence
    DEBUG = True
    try:
        import os as _os
        DEBUG = bool(int(_os.environ.get("CSBOT_DEBUG", "1")))
    except Exception:
        DEBUG = True
        
    def send_threat_alert(process_info, reason):
        name = process_info.get('name', 'Unknown')
        pid = process_info.get('pid', 'Unknown')
        subject = f"🚨 Security Alert: Suspicious Process Detected"
        body = f"""Security Alert: Suspicious Process Detected

Process Details:
- Name: {name}
- PID: {pid}
- Reason: {reason}

This process has been flagged as potentially malicious. Please investigate immediately.

Alert generated by Cybersecurity Bot
"""
        send_email_alert(subject=subject, body=body)
    if DEBUG:
        print("🔍 Scanning processes...")

    for process in psutil.process_iter(['pid', 'name']):
        if stop_event is not None and getattr(stop_event, 'is_set', lambda: False)():
            break
        try:
            name = process.info['name']
            if not name:
                continue

            name_lower = name.lower()
            if DEBUG:
                print(f"Found: {name}")

            # Skip if process is whitelisted
            if name_lower in WHITELIST:
                continue

            # Immediately flag if blacklisted
            if name_lower in BLACKLIST:
                if DEBUG:
                    print(f"🚨 Blacklist match: {name}")
                suspicious.append(process)
                send_threat_alert(process.info, "Process found in blacklist")
                continue

            # Check for suspicious keywords
            if any(keyword in name_lower for keyword in SUSPICIOUS_KEYWORDS):
                if DEBUG:
                    print(f"🚨 Suspicious keyword match: {name}")
                suspicious.append(process)
                matching_keywords = [k for k in SUSPICIOUS_KEYWORDS if k in name_lower]
                send_threat_alert(process.info, f"Suspicious keywords detected: {', '.join(matching_keywords)}")
                continue

            # Behavior check: high CPU or memory usage
            # Use non-blocking CPU sampling to avoid long sleeps during cancellation
            cpu = process.cpu_percent(interval=0.0)
            mem = process.memory_percent()
            if cpu > 50 or mem > 30:
                if DEBUG:
                    print(f"⚠️ High resource usage: {name} (CPU: {cpu}%, MEM: {mem:.2f}%)")
                suspicious.append(process)
                send_threat_alert(process.info, f"High resource usage detected - CPU: {cpu}%, Memory: {mem:.2f}%")

        except (psutil.NoSuchProcess, psutil.AccessDenied, psutil.ZombieProcess):
            continue

    return suspicious